---
- name: Process VMs
  loop: "{{ cluster_nodes }}"
  loop_control:
    loop_var: node_item
  include: remove_vmware_infra.yml

- name: Delete the iso if present
  community.vmware.vsphere_file:
    host: '{{ vcenter_fqdn | b64decode }}'
    username: '{{ vcenter_username | b64decode }}'
    password: '{{ vcenter_password | b64decode }}'
    validate_certs: "{{ (skip_ssl_validation|b64decode == 'true') | ternary('false', 'true') }}"
    datacenter: "{{ vsphere_datacenter }}"
    datastore: "{{ vsphere_datastore }}"
    path: "ISOs/ocp_ai.iso"
    state: absent
  ignore_errors: yes